#lang racket

(define (make-account balance secret-password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        (error "Insufficient funds")))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch name)
    (cond ((eq? name 'withdraw) withdraw)
          ((eq? name 'deposit) deposit)
          (else (error "Invalid option"))))
  (define (checker password operation)
    (cond ((eq? password secret-password)
           (dispatch operation))
          (else (error "Incorrect password"))))
  (define (secure-checker current-retries max-retries)
    (lambda (password operation)
      (cond ((eq? password secret-password)
             (begin (set! current-retries 0)
                    (dispatch operation)))
            ((>= current-retries max-retries)
             (call-the-cops))
            (else
             (begin (set! current-retries (+ 1 current-retries))
                    (error "Incorrect password"))))))
  (define (call-the-cops)
    (display "Cops are coming!!!"))
  (secure-checker 0 3))

