#lang racket

(define (make-account-old balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        (error "Insufficient funds")))
  (define (deposit amount)
    (begin
      (set! balance (+ balance amount))
      balance))
  (define (dispatch name amount)
    (cond ((eq? name 'withdraw) (withdraw amount))
          ((eq? name 'deposit) (deposit amount))
          (else (error "Invalid option"))))
  dispatch)

(define (make-account balance secret-password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        (error "Insufficient funds")))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch name)
    (cond ((eq? name 'withdraw) withdraw)
          ((eq? name 'deposit) deposit)
          (else (error "Invalid option"))))
  (define (checker password operation)
    (cond ((eq? password secret-password)
           (dispatch operation))
          (else (error "Incorrect password"))))
  checker)

